language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm i
    - npm run cy:verify
    - npm run cypress:run

defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - cd $TRAVIS_BUILD_DIR
    - npm run cypress:run
    - echo $TRAVIS_BUILD_DIR
    - cat output.html
    - curl -s --user 'api:5399531559cc4f1362bdd868c2db51e3-d5e69b0b-af9429da' https://api.mailgun.net/v3/sandboxbde6ba4aad6e4be892414b09322d2c8f.mailgun.org/messages \
     -F from='Mailgun Sandbox <postmaster@sandboxbde6ba4aad6e4be892414b09322d2c8f.mailgun.org>' \
     -F to='Mani kandan <mani12316@gmail.com>' \
     -F subject='Hello Mani kandan' \
     -F text='Congratulations Mani kandan, you just sent an email with Mailgun!  You are truly awesome!'
    - echo "Done"

notifications:
  email:
    on_failure: change
    on_success: change
    
jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME="Cypress on Travis CI"
      <<: *defaults
